services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./.data/neo4j/logs:/logs
      - ./.data/neo4j/plugins:/plugins
      - ./.data/neo4j/data:/data
      - ./.data/neo4j/config:/config
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474" # HTTP port
      - "7687:7687" # Bolt port
    restart: always
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./.data/qdrant:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
